### ISSUE TITLE
Where are all the instances stored?

### ISSUE THREAD

**Issue by iacore** [transfem-org/JoinSharkey#1]
this seems just like a static file that's updated by hand.
https://api.joinsharkey.org/instances.json

**Comment by Mar0xy** [comment]
https://github.com/transfem-org/jskapi/blob/main/data/instances.yml

https://github.com/transfem-org/JoinSharkey/issues/new?assignees=&labels=&projects=&template=submit-an-instance.md&title=Instance%3A+%3CInstanceName%3E
