### ISSUE TITLE
Instance: Fediverse Fun

### ISSUE THREAD

**Issue by OzzyShark** [transfem-org/JoinSharkey#2]
**Server URL:**
https://fediverse.fun

**Tell us about your server:**
_What's unique about your server? Is it a bustling community or a cozy hangout? Is it diligently moderated? Share your server's story!_
General purpose server based in US - currently a cozy hangout, just started. Myself and 2 others are moderators

**Agreement**
Do you consent to the [server guidelines](https://github.com/transfem-org/JoinSharkey/blob/main/SERVER_GUIDELINES.md)?
- [x] Yes, I agree to the server guidelines.

**Comment by Mar0xy** [comment]
Added in [`92975a`](https://git.joinsharkey.org/Sharkey/jskapi/commit/92975a8cbdda32858492a6091eefbbd1724abe34)
